review
VladKvetkin/gophermart pull request #1
Opened 2023-08-11 16:36 UTC by VladKvetkin

2023-08-15 19:48 UTC, valentinsoe commented
> Тестировал с помощью автотестов от практикума, поэтому свои не стал писать. Если нужно, то сделаю, без проблем.

Лучше конечно добавить свои. Автотесты от практикума имеют весьма небольшое покрытие.
Не надо писать тесты на все-все-все, но на методы имею какую-либо логику - стоит написать.

2023-08-15 20:52 UTC, valentinsoe requested changes
Спасибо за работу!
Круто что сделал работу так быстро! В целом все просто, понятно и аккуратно, но есть еще над чем поработать:)
Написал замечания по коду.

Также из того что не написал. В коде нет ни одного интерфейса, написать тесты к такому коду будет очень больно.
Рекомендую вынести бизнес-логику из хендлеров отдельный слой. Чтобы хендлеры занимались только разбором запроса и формированием ответа.

Также рекомендую получше проработать вопрос запросов к accrual-серверу. Во-первых делать их многопоточно, во-вторых учитывать код ответа 429 в логике.
Также если заказов "в обработке" скопиться много - мы будем получать из базы огромное количество данных за раз и пытаться его обработать. Это будет очень неэффективно.

В общем из того, что точно стоит доделать:
1) проработать транзакционность(там где сейчас ошибочное поведение в случае параллельных запросов)
2) поработать над снижением связности пакетов(интерфейсы), проще всего это прочуствовать написав тесты
3) реализовать более сложную систему работы с accrual-сервисом(многопоточность, обработку кодов ответов от него). Сохранение даты последней "проверки" статуса и проверку только тех, которые не проверяли достаточно давно.
Намазать это все каналами и прочими штуками из курса:)

2023-08-15 20:52 UTC, valentinsoe commented on cmd/gophermart/main.go
> +	var (
Я бы пересмотрел подход к названиям, чтобы не делать подобный var

2023-08-15 20:52 UTC, valentinsoe commented on internal/accrualer/accrualer.go
> +type Accrualer struct {
Не очень конструктивно, но мне не нравится название:)

2023-08-15 20:52 UTC, valentinsoe commented on internal/accrualer/accrualer.go
> +	client := ac.initClient()
Каждый раз инициализировать новый клиент нет необходимости.
К тому же, я бы настоятельно рекомендовал отделить accrualer от accrualHttpClient.
Чтобы можно было например написать тесты, подменив реализацию клиента

2023-08-15 20:52 UTC, valentinsoe commented on internal/accrualer/accrualer.go
> +	for _, order := range orders {
Такой подход конечно делает максимально простым код, но однопоточное обращение во внешний сервис - это нежизнеспособно. Если на сетевые задержки уходит 100ms, то мы не можем делать более 10 запросов в секунду.

2023-08-15 20:52 UTC, valentinsoe commented on internal/accrualer/accrualer.go
> +	for _, order := range orders {
С учетом встроенных retry клиента - получим потенциально еще более низкую пропускную способность.

2023-08-15 20:52 UTC, valentinsoe commented on internal/accrualer/accrualer.go
> +	if response.StatusCode() != http.StatusOK {
На коды 204 и 429 должна быть корректная реакция, а не просто запись в лог.

2023-08-15 20:52 UTC, valentinsoe commented on internal/accrualer/accrualer.go
> +	client := ac.initClient()
Ну и в целом одно - реализация протокола внешнего сервиса. Другое - бизнес-логика работы с ним:)

2023-08-15 20:52 UTC, valentinsoe commented on internal/entities/order.go
> +type Withdrawn struct {
Занудство чистой воды:
Сущность лучше назвать Withdrawal  - существительным, а не глаголом в прошедшем времени

2023-08-15 20:52 UTC, valentinsoe commented on internal/entities/orderwithdraw.go
> +type OrderWithdraw struct {
Копия типа Withdrawn, которая нигде не используется:)

2023-08-15 20:52 UTC, valentinsoe commented on internal/entities/order.go
> +	CreatedAt time.Time `db:"created_at"`
updated_at поле бы тоже тут пригодилось.
Как для отладки, так и для других целей(об этом будет в другом комментарии)

2023-08-15 20:52 UTC, valentinsoe commented on internal/handler/balance.go
> +	userID, ok := req.Context().Value(middleware.UserIDKey{}).(string)
Я бы спрятал это в функцию helper, чтобы не писать такую объемную конструкцию почти в каждом хендлере.

2023-08-15 20:52 UTC, valentinsoe commented on internal/handler/balance.go
> +func (h *Handler) Withdraw(res http.ResponseWriter, req *http.Request) {
Занудство: унести в отдельный файл.

2023-08-15 20:52 UTC, valentinsoe commented on internal/handler/balance.go
> +	currentAccrual, err := h.storage.GetUserAccrual(req.Context(), userID)
Такая работа с балансом позволит при двух одновременных запросах увести баланс в минус.
Стоит написать защиту от этого.

2023-08-15 20:52 UTC, valentinsoe commented on internal/handler/login.go
> +	userID, err := h.storage.GetUser(req.Context(), requestModel.Login, h.generatePasswordHash(requestModel.Password))
Некритичное замечание, но так как сервис "финансовый", рекомендую почитать про "соление" паролей:)

2023-08-15 20:52 UTC, valentinsoe commented on internal/handler/orders.go
> +			if _, err := h.storage.CreateOrder(req.Context(), userID, orderNumberString); err != nil {
Фатального ничего не произойдет, но при одновременной попытке создать заказ с одинаковым номером - кто-то получит 500(а не 409 или 200) из-за unique constraint  в postgres

2023-08-15 20:52 UTC, valentinsoe commented on internal/middleware/auth.go
> +		if isSkipCheckAuth(req.URL.Path) {
Не самый лучший подход к исключению проверки куки для некоторых хендлеров.
Лучше добавить эту middleware только на конкретные хендлеры(группы хендлеров).

2023-08-15 20:52 UTC, valentinsoe commented on internal/server/routes.go
> +	s.mux.Route("/", func(r chi.Router) {
Chi позволяет делать группы маршрутов. И для некоторых можно исключить auth middleware.
Иначе у нас тут "захардкожены" пути, а также их часть в auth middleware захардкожена.

2023-08-15 20:52 UTC, valentinsoe commented on internal/services/validation/luhn.go
> +	return goluhn.Validate(value)
В порядке "зарядки" для мозга рекомендую попробовать самому реализовать алгоритм(необязательно)

2023-08-15 20:52 UTC, valentinsoe commented on internal/storage/postgres.go
> +			return "", ErrConflict
Мы не анализируем эту ошибку в коде, где вызываем этот метод

2023-08-15 20:52 UTC, valentinsoe commented on internal/storage/postgres.go
> +	row := s.db.QueryRowxContext(ctx, "SELECT SUM(withdrawn) FROM orders_withdraw WHERE user_id = $1;", userID)
Баланс мы храним в пользователе. А почему бы нам также не хранить и сумму, которую списали?

2023-09-06 07:35 UTC, VladKvetkin commented
Привет. Спасибо за развернутые комментарии, со всем согласен, но удалось внести правки лишь частично. Немного устал от обучения, поэтому не все сделал. Если есть возможность, то прими, пожалуйста, проект на "троечку" :)

2023-09-07 03:14 UTC, valentinsoe approved these changes
Спасибо за откровенность.
Формальные критерии к проекту выполнены. Хотя код мог бы быть значительно аккуратнее:)

2023-09-07 05:58 UTC, merged